### ISSUE TITLE
Discussion on NextStateTable.forward_reduce() and scatter_reduce

### ISSUE THREAD

**Issue by theadamsabra** [google-research/last#31]
hi @kho, would like to get another set of eyes on my torch implementation. while this implementation passes the defined tests, it is very clear it is not robust to numerous samples in a batch. this one is gonna be on the longer side, so a big thank you ahead of time. strap in for the ride.

---
## Some Context

torch's scatter reduce has some different requirements from the XLA you linked in your documentation. in my case, [the three tensors (operand, scatter_indices, updates) must be the same dimensions](https://pytorch.org/docs/stable/generated/torch.Tensor.scatter_reduce_.html#torch.Tensor.scatter_reduce_) which does not seem to be a requirement in your implementation (i.e. `operand` can be the final output shape of the `scatter_reduce`.)

for simplicity, let's consider the case of the [test](https://github.com/google-research/last/blob/main/tests/contexts_test.py#L210-L216) implemented. when entering the method we have:

- `weights.shape == torch.Size([1, 13, 3])`
- using a real semiring
- `scatter_indices.shape == self.next_state_table.shape == torch.Size([13,3])`
- `batch_dims == torch.Size([1])`
- `num_states == 13`
- `vocab_size == 3` (which i kept for tensor shape preservation, [in JAX we could ignore this](https://github.com/google-research/last/blob/main/last/contexts.py#L299))

this is rather straightforward so far on the implementation:
```python
  def forward_reduce(self, weights: torch.Tensor,
                     semiring: semirings.Semiring[torch.Tensor]) -> torch.Tensor:
    batch_dims = weights.shape[:-2]
    if weights.shape[-2:] != self.shape():
      raise ValueError(f'weights.shape[-2:] should be {self.shape()} but got'
                       f' {weights.shape[-2:]}')
    num_states, vocab_size = self.shape()
```

---
## Where Implementations Diverge

when we construct our operand and indices, i diverge slightly from your implementation to ensure `operand`, `scatter_indices`, and `updates` are the same shape as follows:

```python
    # Build the scatter operation.
    operand = semiring.zeros(batch_dims + (num_states,) + (vocab_size,), weights.dtype)
    updates = weights
    scatter_indices = torch.unsqueeze(self.next_state_table, dim=0)
    scatter_dims_to_operand_dims = len(batch_dims)
```

my gut is telling me that there is an issue in this block. you might even see it - but for the life of me, i cannot. for now, let's assume there is nothing wrong and move on with the method implementation. i'll get back to this.

now that i have my necessary tensors (as well as the dim to operate within), we can perform the `scatter_reduce` on operand.

```python
   return operand.scatter_reduce(scatter_dims_to_operand_dims, 
                                scatter_indices.to(torch.int64),
                                updates, 'sum')
```

now, we didn't *really* reduce operand. it's still of shape `torch.Size([1, 13, 3])`. the resulting output is the following:

```python
tensor([[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  1,  0],
         [ 0,  0,  2],
         [66,  0,  0],
         [ 0, 70,  0],
         [ 0,  0, 74],
         [78,  0,  0],
         [ 0, 82,  0],
         [ 0,  0, 86],
         [90,  0,  0],
         [ 0, 94,  0],
         [ 0,  0, 98]]])
```
we see the values we need! to properly reduce the tensor, we can simply get the max values. now the final return value is

```python
    return operand.scatter_reduce(scatter_dims_to_operand_dims, 
                                scatter_indices.to(torch.int64),
                                updates, 'sum').max(dim=-1).values
```
now our output is what we expect:

```python
tensor([[ 0,  0,  1,  2, 66, 70, 74, 78, 82, 86, 90, 94, 98]])
```

the test passed, so everything must be okay, right?

---

## Addressing the Problems

let's say our test was not using a batch size of 1. rather, the test looked something like this:

```python
          context.forward_reduce(
              torch.arange(78).reshape((2, 13, 3)), semirings.Real)
```

then, our desired output is 
```python
tensor([[  0,   0,   1,   2,  66,  70,  74,  78,  82,  86,  90,  94,  98],
       [  0,  39,  40,  41, 222, 226, 230, 234, 238, 242, 246, 250, 254]])
```

however, the output i get is
```python
tensor([[ 0,  0,  1,  2, 66, 70, 74, 78, 82, 86, 90, 94, 98],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])
```

i cannot understand what is causing second batch to be all zeros. i believe the issue is related to the code block i mentioned above, but i do not have conclusive evidence for this being the case. i hope i can get your feedback on this. 

thanks so much for your time!

**Comment by kho** [comment]
Haven't looked too closely but you don't have to waste your time on scatter_reduce on NextStateTable. It was part of a failed experiment that never worked out.

**Comment by theadamsabra** [comment]
Interesting - thanks for the heads up. 

If this is the case, should the forward reduce be implemented at all?

**Comment by kho** [comment]
`forward_reduce()` is part of the `ContextDependency` interface. You will still need it for `FullNGram`.

**Comment by theadamsabra** [comment]
Thanks @kho. 

I'll keep the current implementation as is since it passes tests. If someone decides to use it I'll prioritize fixing the bug for N batches.
