### ISSUE TITLE
Needing to Implement Scan from Scratch

### ISSUE THREAD

**Issue by theadamsabra** [google-research/last#32]
hey @kho, had a question about the [the following code block](https://github.com/google-research/last/blob/main/last/lattices.py#L377-L381). for context, the shapes come from the [build_cache of `lattices_test`](https://github.com/google-research/last/blob/main/last/lattices.py#L377-L381).

--

by the time we reach this point:

`init_alpha` is of shape (4,5)
`blank_weight` and `lexical_weight` is of shape (4, 6, 5). however, it gets permuted via `_to_time_major` to (6,4,5).

when we scan, we will iterate 6 times, with a final shape of alpha being (4,5). if i understand the code correctly, are we updating alpha every pass in the scan?

you can see my implementation here:

```python
def shortest_distance_step_scan(shortest_distance_step, init, xs):
  
  t, alpha = init
  blank_weight, lexical_weight = xs

  for i in range(blank_weight.shape[0]):
    (t, alpha), _ = shortest_distance_step(alpha, (blank_weight[i,:], lexical_weight[i,:]))

  return (None, alpha), None
```

**Comment by kho** [comment]
Yes. alpha is [batch_size, num_context_states]. In each scan step, we compute alpha for that input frame t so that after the step alpha[:, q] is the sum of all paths entering state q after observing input frame t.

**Comment by theadamsabra** [comment]
Thanks. 

If I understand the shortest_distance_step correctly, alpha is updated as a matrix, not row by row.

So we do not need to feed in alpha[:q] in the scan, but rather iteratively update the entire matrix. Am I correct in this understanding?

**Comment by kho** [comment]
No, we just need the alpha from the last frame.

**Comment by theadamsabra** [comment]
perfect. got a working solution with minor tweaks. thanks for your help!
